
export const signUpController = async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(`ERROR WHILE SINGNUP`)
    }
}

export const loginController = async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(`ERROR WHILE LOGIN`)
    }
}

export const logoutController = async(req,res)=>{
    try {
        
    } catch (error) {
        console.log(`ERROR WHILE LOGOUT`)
    }
}